### ISSUE TITLE
Quite literally, doesn't want to run. [MultiMC]

### ISSUE THREAD

**Issue by conc1erge** [Noxiuam/Reliant#9]
Maybe it might just be me using MultiMC, but this is the error that I get that makes it not want to enter the main menu screen.

```
[Reliant] [INFO] (Initialization) Created Logger
[Reliant] [INFO] (Bridge Implementation) Setup Bridge Implementation
[Reliant] [INFO] (Bridge) Minecraft Bridge is "MinecraftAppletImpl"
[Reliant] [INFO] (Initialization) Created Bridge
[Reliant] [INFO] (Initialization) Created Command Manager
java.lang.NullPointerException
	at gq.noxiuam.reliant.client.module.ModuleManager.<init>(ModuleManager.java:58)
	at gq.noxiuam.reliant.client.Reliant.<init>(Reliant.java:59)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:266)
	at net.minecraft.client.Minecraft.run(Minecraft.java:498)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by Noxiuam** [comment]
might look into this later
